Repository relyt4me/RefactorTractor-FitLit, pull requests merged in 2020-07, with the labels that each got.

#16 Create DTR.md
  .github/DTR.md
Labels: documentation

#33 Cc user rename
  src/User-repo.js
  src/User.js
  src/scripts.js
  test/user-test.js
  test/userrepo-test.js
Labels: Javascript, testing

#35 Jms activity class initial clean up
  src/Activity.js
  test/activity-test.js
Labels: Javascript, documentation, enhancement

#36 Cc fetch all data
  src/Sleep.js
  src/scripts.js
Labels: enhancement

#38 Cc css html rework
  src/css/_main-section.scss
  src/css/_mixins.scss
  src/css/_right-side.scss
  src/css/_user-card.scss
  src/css/_variables.scss
  src/css/style.scss
  src/index.html
  src/scripts.js
Labels: CSS, Refactor, enhancement

#37 Th refactor sleep
  src/Sleep.js
  test/sleep-test.js
Labels: Javascript, Refactor, dependencies

#41 Revert "Cc css html rework"
  src/css/_main-section.scss
  src/css/_mixins.scss
  src/css/_right-side.scss
  src/css/_user-card.scss
  src/css/_variables.scss
  src/css/style.scss
  src/index.html
  src/scripts.js
Labels: CSS, HTML, Javascript, enhancement

#39 Jms activity class friends refactor
  src/Activity.js
  test/activity-test.js
  test/sampleData/activitySampleData.js
Labels: Javascript, Refactor, enhancement, testing

#51 Cc spies testing
  src/DomUpdates.js
  src/scripts.js
  test/DomUpdates-test.js
  test/sleep-test.js
  test/userrepo-test.js
Labels: Javascript, testing

#52 Th css layout
  src/css/_main-section.scss
  src/css/_mixins.scss
  src/css/_right-side.scss
  src/css/_user-card.scss
  src/css/_variables.scss
  src/css/base.scss
  src/css/style.scss
  src/index.html
Labels: Accessibility, CSS, HTML, enhancement

#54 Create framework of posting all user data function
  src/postAllUserData.js
Labels: Get/Post, Javascript, good first issue

#59 Jms activity dom updates
  src/Activity.js
  src/DomUpdates.js
  src/Sleep.js
  test/activity-test.js
Labels: Javascript

#60 Cc dom sleep challenge
  src/DomUpdates.js
  src/Sleep.js
  src/index.html
  src/scripts.js
Labels: Javascript

#62 Jms post user input
  src/css/_user-card.scss
  src/index.html
  src/scripts.js
Labels: Javascript, enhancement, question

#71 Cc tabbing and accessability
  README.md
  src/Hydration.js
  src/Sleep.js
  src/User.js
  src/css/_main-section.scss
  src/css/_right-side.scss
  src/css/_user-card.scss
  src/css/style.scss
  src/index.html
  src/postAllUserData.js
  src/scripts.js
  test/DomUpdates-test.js
  test/sleep-test.js
Labels: Accessibility, CSS, HTML, enhancement, testing

#70 Jms activity cleanup
  src/Activity.js
  test/activity-test.js
Labels: Javascript, enhancement

#72 Jms code cleanup
  .DS_Store
  src/Activity.js
  src/DomUpdates.js
  src/Sleep.js
  src/css/_main-section.scss
  src/css/_right-side.scss
  src/css/_user-card.scss
  src/css/_variables.scss
  src/css/base.scss
  src/css/style.scss
  src/data/activity.js
  src/data/hydration.js
  src/data/sleep.js
  src/data/users.js
  src/postAllUserData.js
  src/scripts.js
  test/.DS_Store
  test/activity-test.js
  test/hydration-test.js
  test/sleep-test.js
  test/user-test.js
  test/userrepo-test.js
Labels: Refactor, enhancement

#78 Add color function and change coloring slightly
  src/css/_mixins.scss
  src/css/_variables.scss
  src/css/style.scss
Labels: Accessibility, CSS

#81 Jms fetch bug fix
  src/DomUpdates.js
  test/activity-test.js
Labels: enhancement

#82 Cc passing tests
  test/DomUpdates-test.js
  test/activity-test.js
Labels: testing
